services:
  backend:
    build: ./
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=postgres
    networks:
      - backendN
  db:
    image: postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/data/postgres
    networks:
      - backendN
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    depends_on:
      - backend
    ports:
      - 80:80
    networks:
      - backendN


volumes:
  postgres:

networks:
  backendN:
